on: 
  push:
    branches-ignore: main

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: registry.fly.io/shirtscanner-fe:${{ github.sha }}