on:
  pull_request:

name: Dependabot Auto merge
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: buluma/dependabot-auto-merge-action@v2
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}