on: 
  push:
    branches: main

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1.4

      - name: Login to Docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl auth docker

      - name: Build
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: registry.fly.io/shirtscanner-fe:${{ github.sha }}
          load: true
      
      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy -i registry.fly.io/shirtscanner-fe:${{ github.sha }}